Setting.create!([
  {namespace: "company_name", value: {"value"=>"Woffice"}},
  {namespace: "square_key", value: {"value"=>"EAAAEH83t1qbAPHypGll3SImNboOkHzhbVZn2XmOIq21ItYy8BXWGrRmXjRUgTaG"}},
  {namespace: "square_app_id", value: {"value"=>"sandbox-sq0idb-g75z4FJpMVE0s9qUn7GTmQ"}},
  {namespace: "mail_to_customer", value: {"value"=>{"send_from"=>"Customer", "template_id"=>"d-209a08276e804f778e57cefb058b52d1", "objects"=>[{"class"=>"Customer", "fields"=>[{"field"=>"nome_categoria", "sendgridkey"=>"metodo"}, {"field"=>"notes", "sendgridkey"=>"notes"}]}]}}},
  {namespace: "authenticity_token", value: {"value"=>"HB+bqeBERq4poHPEJIhocg7OC4fghc3aXcS41vM+ONYHyPZzEU1HqLv6JTRMbnQ6cUkDLh4MKQDYgO9gQD8Ebw=="}},
  {namespace: "logo", value: {"value"=>"https://woodoffice.s3-sa-east-1.amazonaws.com/uploads/document_file/file/105/Whats-App-Image-2020-04-02-at-12-51-26.jpg?X-Amz-Expires=600&X-Amz-Date=20200414T213423Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJNURU3YPPX7JTHGA%2F20200414%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=b633f7970bb860b9533ab9191708d3268cbec8204e161cd5f90937fa837403c9"}},
  {namespace: "client_end_order", value: {"value"=>true}},
  {namespace: "take_photo", value: {"value"=>true}},
  {namespace: "sign_order_mail_text", value: {"value"=>"Assina ae"}},
  {namespace: "send_square_mail_text", value: {"value"=>"Pay Text example"}},
  {namespace: "square_oauth_secret", value: {"value"=>"sandbox-sq0csb-RTkiAws8xoQF5DqMQb7aDu7HwJn-FEaek3mlUdy521g"}},
  {namespace: "square_oauth_access_token", value: {"value"=>"EAAAEH_3Ge7kzP-jmlwkiILsC8zjeYOzjTVlAyT2qSI328oSzU3e0PKLeOyqe3Of"}},
  {namespace: "square_oauth_refresh_token", value: {"value"=>"EQAAEARdjLS3OGJ4mWreHlwKBeC9mVtBnC2LQ5sj5jpz4YGsKG7UxwR89liRPQCb"}},
  {namespace: "square_oauth_code", value: {"value"=>"sandbox-sq0cgb-8sdBu2FJqVfMj1LBJYxR5w"}},
  {namespace: "send_grid_key", value: {"value"=>"sandbox-sq0cgb-8sdBu2FJqVfMj1LBJYxR5w"}},
  {namespace: "hidden_measurement_fields", value: {"value"=>{"width"=>false, "length"=>true, "height"=>true, "square_feet"=>false}}},
  {namespace: "send_document_mail_text", value: {"value"=>"Text example documento"}},
  {namespace: "company_full_name", value: {"value"=>"teste fulll name"}},
  {namespace: "company_address", value: {"value"=>"endereco"}},
  {namespace: "send_invoice_mail_text", value: {"value"=>"Text example invoice"}},
  {namespace: "company_phone", value: {"value"=>"(123) 213-2131"}},
  {namespace: "company_email", value: {"value"=>"teste@teste.com"}},
  {namespace: "order_need_sign", value: {"value"=>true}},
  {namespace: "estimate_notes", value: {"value"=>"<p>teste do estimate <strong>notes</strong></p><p><br></p><p><strong>testando teste</strong></p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>"}}
])
